exclude_paths:
  - "**LICENSE**"
  - "**.md"
  - "**.toml"
  - "**.yaml"
  - "**.lock"
  - "**/*test_*.rs"
  - "**/mod.rs"
  - "**/lib.rs"
  - "**/main.rs"
  - "**/.github/**"
  - "**/target/**"
  - "**/Cargo.lock"
  - "**/Cargo.toml"
  - "Makefile"