name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install Rust
      run: rustup update stable
    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov
    # - name: Install Clippy
    #   run: rustup component add clippy
    # - name: Install cargo-sonar and run Clippy
    #   run: |
    #     cargo install cargo-sonar
    #     cargo clippy --message-format > my-clippy-report.json
    #     cargo sonar --clippy --clippy-path my-clippy-report.json
    - name: Build
      run: cargo build --verbose
    - name: Run tests with coverage
      run: ./.github/scripts/run-cov.sh
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
