name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install Rust
      run: rustup update stable
    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov
    - name: Build
      run: cargo build --verbose
    - name: Run tests with coverage
      run: ./.github/scripts/run-cov.sh
    - name: Report coverage to Codacy
      uses: codacy/codacy-coverage-reporter-action@v1.3.0
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: target/coverage/coverage.xml
        language: rust
  # codacy-coverage-reporter:
  #   runs-on: ubuntu-latest
  #   name: codacy-coverage-reporter
  #   needs: build
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Run codacy-coverage-reporter
  #       uses: codacy/codacy-coverage-reporter-action@v1.3.0
  #       with:
  #         project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
  #         coverage-reports: target/coverage/coverage.xml
  #         language: rust